# Generated by Django 6.0.5 on 2026-05-09 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('store_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(choices=[('food', 'Food'), ('beverage', 'Beverage'), ('snacks', 'Snacks'), ('utilities', 'Utilities'), ('personal_care', 'Personal Care'), ('others', 'Others')], default='others', max_length=50)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('source', models.CharField(choices=[('ocr', 'OCR Assisted'), ('manual', 'Manual Entry')], default='manual', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
