# Generated by Django 6.0.5 on 2026-05-09 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='receipts/')),
                ('raw_ocr_text', models.TextField(blank=True, null=True)),
                ('extracted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extracted_date', models.DateField(blank=True, null=True)),
                ('extracted_store', models.CharField(blank=True, max_length=255, null=True)),
                ('extracted_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
